#!/usr/bin/env perl
use Mojolicious::Lite;

plugin 'Config';

get '/' => sub {
  my $c = shift;
  $c->render(template => 'index');
};
get '/new' => sub {
  my $c = shift;
};
post '/new' => sub {
  my $c = shift;
  my $client_name = $c->param('client_name');
  my $aws_account = $c->param('aws_account');
  # insert into kms (client_name, aws_account) values ($client_name, $aws_account)
  $c->render('new_saved');
};
get '/fake_aws_console' => sub {
  my $c = shift;
  my $account = $c->param('account');
  # my $client_name = select client_name from kms where aws_account = '$account'
  my $client_name = $c->param('roleName'); $client_name =~ s/-.*?$//;
  $c->stash(client_name => $client_name);
};

get '/console' => sub {
  my $c = shift;
  my $client_name = $c->param('client_name');
  $c->redirect_to("/console/$client_name");
};
get '/console/:client' => sub {
  my $c = shift;
  my $role_suffix = $c->app->config->{role_suffix};
  my $client = $c->param('client');
  $c->redirect_to("/fake_aws_console?account=12345&roleName=${client}$role_suffix&displayName=KMS+\@+$client") unless $c->app->config->{links}->{$client};

  # my %client = select aws_account, client_name from kms where client_name='$client' or aws_account='$client'
  my $console_url = $c->app->config->{console_url};
  my %client = %{$c->app->config->{links}->{$client}};
  $console_url =~ s/%aws_account%/$client{aws_account}/g;
  $console_url =~ s/%client_name%/$client/g;
  $console_url =~ s/%role_suffix%/$role_suffix/g;
  $console_url =~ s/%display_name%/KMS+\@+$client{display_name}/g;
  $c->redirect_to($console_url);
};
get '/lookup/:client' => sub {
  my $c = shift;
  my $client = $c->param('client');
  # my @options = select client_name from kms where client_name like "%$client%" or aws_account like "%$client%"
  my $options = $c->app->config->{links};
  $options = {map { $_ => $options->{$_} } grep { $_->{display_name} =~ $client || $_->{aws_account} =~ $client } keys %$options} if $client;
  $c->render(json => {clients => [keys %$options]});
};

app->start;
__DATA__

@@ fake_aws_console.html.ep
<p>This a a fake representation of the client's AWS console that you would be seeing if this wasn't a prototype.</p>
<p>You probably requested a different client than the details below, but this is just a prototype.</p>
You have connected to <%= $client_name %><br>
<li>Account: <%= param 'account' %></li>
<li>roleName: <%= param 'roleName' %></li>
<li>displayName: <%= param 'displayName' %></li>

@@ new.html.ep
%= form_for new => (method => 'POST') => begin
  %= label_for client_name => 'Client Name'
  %= text_field 'client_name'
  %= label_for aws_account => 'Client AWS Account #'
  %= text_field 'aws_account'
  %= submit_button
% end
<p>Alternatively, we could prompt fo the client's AWS API credentials (key and secret)<p>

@@ new_saved.html.ep
Almost done with onboarding!  Log into to your client's AWS console (perhaps as the client's root account?) and create these roles and policies:
<p>Create a policy for <%= config 'company' %></p>
<li><%= config 'company_role' %></li>
<p>Create a role</p>
<li><%= param 'client_name' %><%= config 'role_suffix' %></li>
<p>Assign the policy to the role with these options:</p>
<li>Role for cross-account access</li>
<li>Provide access between AWS accounts you own</li>
<li>Enter <%= config 'company' %> Account ID <%= config 'MSP_AWS_ID' %></li>
<p>Or, if using AWS API creds do all that stuff automatically</p>
<hr>
<p>Click this button to continue: [pretend this is a button and you just clicked it]</p>
<hr>
You just on-boarded <%= param 'client_name' %>!  (You didn't really, this is just a prototype.)<br>
What that means is:
<li>You can now visit <%= link_to 'the KMS AWS Orchestration Tool' => '/' %> to connect to this client's AWS console.</li>
<li>You can now jump straight to this client's AWS console by <%= url_for('consoleclient', client => param 'client_name')->to_abs %></li>
<li>This KMS AWS Orchestration Tool just connected to the KMS AWS API and modified to append the following JSON statement to the role's policy named "AssumeRoleFullAccess" for group "Administrators":</li>
<pre>
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "arn:aws:iam::<%= param 'aws_account' %>:role/<%= param 'client_name' %><%= config 'role_suffix' %>"
        }
</pre>
<li>Any KMS AWS user that is in the Administrators group can manage the AWS console of this client (or any client because we decided that the Administrators group should be able to connect to any KMS client).

@@ index.html.ep
% layout 'default';
% title config 'name';
<h1>Welcome to <%= config 'company' %>'s first in-house AWS orchestration tool!</h1>
<p><%= link_to 'Click here to connect to the KMS AWS console' => 'http://aws.kit.cm' %></p>
<p>(Provide some hint documentation here that instructs / reminds the <%= config 'company' %> employee what is in this console, how they login to it, and why they use it.)</p>

<p>This is for managing <%= config 'name' %> clients' AWS consoles:</p>
<p>[ <%= link_to '+' => 'new' %> ] On-board a new KMS client's AWS console to be managed by KMS.<p>
<p>Manage a recently managed KMS client by selecting from the history list:</p>
% my $options = config 'links';
% foreach ( keys %$options ) {
<li><%= link_to $_ => url_for 'consoleclient', client => $_ %></li>
% }
<p>Or specify on this auto-complete form which client you wish to connect to:<p>
<p>(auto-complete not currently enabled)</p>
%= form_for console => begin
  %= label_for client_name => 'Client Name or AWS Account #'
  %= text_field 'client_name'
  %= submit_button
% end

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
